# -*- coding: utf-8 -*-
"""FDS_Lab_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EG1vHNzKMdIIKcw6eVMc5x5A1nGpivH4

**Importing Libraries**

    * Pandas for reading data file
    * Numpy for performing statistical calculations
    * Matplotlib and seaborn for visualization
    * Scipy.stats for Skewness and Kurtosis
"""

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from scipy.stats import skew
from scipy.stats import kurtosis

"""***To see all the columns which are present in the dataset***"""

pd.set_option("display.max_columns",None)#To see all the columns which are present in the dataset

"""***#Mounting Google Drive***"""

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

"""***Unzip the dataset.zip.***"""

dir =" ";
import zipfile
zip_ref = zipfile.ZipFile("/content/gdrive/MyDrive/Data.zip",'r')
zip_ref.extractall(dir)
zip_ref.close()

!wget /content/gdrive/MyDrive/Data.xlsx

!unzip /content/gdrive/MyDrive/Data.xlsx

"""
**Reading dataset**

    df is dataframe .
    pd.read_excel reads the excel file.
    head Function prints the first five rows of the dataset. *italicized text*

**Description of data**

    Data belongs to student category which contains fname , age and gender column.
    Fname contins the name of students, age column contains the age of the students and grade column contains the marks obtained. *italicized text*


"""

df=pd.read_excel("/ /Data.xlsx")
df.head()

"""
**Measures of Central Tendency**

    Mean
        The sum of a collection of numbers divided by the count of numbers in the collection.
  
    Median
        The median is the value separating the higher half from the lower half of a data sample, a population, or a probability distribution.
   
    Mode
        The mode is the value that appears most often in a set of data values.


**Where the measures of central tendency used?**

    The above three values are used in handling null and outlier values in Machine learning, in Image processing mean and median plays an important role , we use mean and median for applying threshold values on the particular image.
    cv2.ADAPTIVE_THRESH_MEAN_C threshold value is the mean of neighbourhood area.

    cv2.medianBlur() computes the median of all the pixels under the kernel window and the central pixel is replaced with this median value.


"""

df_mean=df.mean()
print("*Mean of columns age and grade*")
print(df_mean)
df_median=df.median()
print("*Median of columns age and grade*")
print(df_median)
df_mode=df.mode()
print("*Mode of columns age and grade*")
print(df_mode)

"""
**Measures of Variability**

    Standard Deviation
       The standard deviation is a measure of the amount of variation or dispersion of a set of values.
    
    Variance
        The term variance refers to a statistical measurement of the spread between numbers in a data set.
   
    Min and Max Variables
        Min is the minimum value in the column or in dataset.
        Max is the maximum value in the column or in dataset.

**Where the measures of variability is used?**

    Standard deviation is used to know how data is spread so we can find some good insigths from it.
    Example:-

        If we are working with data which consist column of years, tax rate, sales amount etc. so, after applying standard deviation we will get to know at which year the tax rate or sales amount was more or less.
        
    Min and Max both are used to find range of the array or particilar column, so we can detect the outliers.


"""

print("Standard deviation of columns age and grade")
print(df.std())
print("Variance of columns age and grade  ")
print(df.var())
print("The Minimum value are" )
print(df.min())
print("The Maximum value are" )
print(df.max())

"""

    Skewness and Kurtosis

        Skewness is a measure of the symmetry of a distribution. The highest point of a distribution is its mode.
        Kurtosis is a statistical measure that defines how heavily the tails of a distribution differ from the tails of a normal distribution.

**Where do we use Skewness and Kurtosis ?**

    Skewness can be used to obtain approximate probabilities and quantiles of distributions (such as value at risk in finance) via the Cornish-Fisher expansion.
    
    Kurtosis is used to describe the extreme values in one versus the other tail. It is actually the measure of outliers present in the distribution . High kurtosis in a data set is an indicator that data has heavy tails or outliers.


"""

age_skew=skew(df["age"])
grade_skew=skew(df["grade"])
print("The skewness of column age is : ",age_skew)
print("The skewness of column grade is : ",grade_skew)

age_kurtosis=kurtosis(df["age"])
print("The kurtosis of column age is ",age_kurtosis)
grade_kurtosis=kurtosis(df["grade"])
print("The kurtosis of column grade is ",grade_kurtosis)

"""
 * Range
        The Range is the difference between the lowest and highest values.

    Given that the range can easily be computed with information on the maximum and minimum value of the data set.

    Users requiring only a rough indication of the data may prefer to use this indicator over more sophisticated measures of spread.


"""

age_range=(df["age"].max())-(df["age"].min())
print("The range of column age is :",age_range)

grade_range=(df["grade"].max())-(df["grade"].min())
print("The range of column grade is :",grade_range)

"""

 * Percentiles/Quartiles
        A percentile is a measure at which that percentage of the total values are the same as or below that measure. For example, 90% of the data values lie below the 90th percentile, whereas 10% of the data values lie below the 10th percentile.

        Quartiles are values that divide a (part of a) data table into four groups containing an approximately equal number of observations. The total of 100% is split into four equal parts: 25%, 50%, 75% and 100%.

    Percentiles are used to understand and interpret data.
    Quartiles are used to summarize a group of numbers.


"""

print("50th percentile of age column is:",np.percentile(df["age"],50))
print("25th percentile of age column is:",np.percentile(df["age"],25))
print("75th percentile of age column is:",np.percentile(df["age"],75))

print("50th percentile of grade column is:",np.percentile(df["grade"],50))
print("25th percentile of grade column is:",np.percentile(df["grade"],25))
print("75th percentile of grade column is:",np.percentile(df["grade"],75))

print("Q2th quantile of age column is : ",np.quantile(df["age"],.50))
print("Q1th quantile of age column is : ",np.quantile(df["age"],.25))
print("Q3th quantile of age column is : ",np.quantile(df["age"],.75))

print("Q2 quantile of grade column is : ",np.quantile(df["grade"],.50))
print("Q1th quantile of grade column is : ",np.quantile(df["grade"],.25))
print("Q3 quantile of grade column is : ",np.quantile(df["grade"],.75))

"""

  * Box Plots
        A box and whisker plot (sometimes called a boxplot) is a graph that presents information from a five-number summary.
        Lowest observation
        Highest observation
        Lower Quartile
        Upper Quartile
        Median


"""

plt.figure()
plt.subplot(1,2,1)
df.boxplot(column="age")
plt.subplot(1,2,2)
df.boxplot(column="grade")
plt.show()